// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _27_FrontToBackSqlConnection.Data;

#nullable disable

namespace _27_FrontToBackSqlConnection.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260508011016_AddProducts")]
    partial class AddProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("_27_FrontToBackSqlConnection.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoverImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsBestSeller")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<bool>("IsNew")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A bright flowering plant for balconies, gardens, and warm indoor corners.",
                            HoverImage = "1-2-270x300.jpg",
                            Image = "1-1-270x300.jpg",
                            IsBestSeller = true,
                            IsFeatured = true,
                            IsNew = false,
                            Name = "American Marigold",
                            Price = 23.45m,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Compact, cheerful blooms with easy care needs and long seasonal color.",
                            HoverImage = "1-3-270x300.jpg",
                            Image = "1-2-270x300.jpg",
                            IsBestSeller = false,
                            IsFeatured = true,
                            IsNew = false,
                            Name = "Black Eyed Susan",
                            Price = 25.45m,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Elegant heart-shaped flowers for soft shade and decorative garden beds.",
                            HoverImage = "1-4-270x300.jpg",
                            Image = "1-3-270x300.jpg",
                            IsBestSeller = false,
                            IsFeatured = false,
                            IsNew = true,
                            Name = "Bleeding Heart",
                            Price = 30.45m,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A resilient perennial with rich color and a tidy spreading habit.",
                            HoverImage = "1-5-270x300.jpg",
                            Image = "1-4-270x300.jpg",
                            IsBestSeller = true,
                            IsFeatured = false,
                            IsNew = false,
                            Name = "Bloody Cranesbill",
                            Price = 45.00m,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A sun-loving plant with vivid blooms and pollinator-friendly growth.",
                            HoverImage = "1-6-270x300.jpg",
                            Image = "1-5-270x300.jpg",
                            IsBestSeller = false,
                            IsFeatured = false,
                            IsNew = true,
                            Name = "Butterfly Weed",
                            Price = 50.45m,
                            isDeleted = false
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Hardy clusters of flowers that fit naturally into low-maintenance gardens.",
                            HoverImage = "1-7-270x300.jpg",
                            Image = "1-6-270x300.jpg",
                            IsBestSeller = false,
                            IsFeatured = true,
                            IsNew = false,
                            Name = "Common Yarrow",
                            Price = 65.00m,
                            isDeleted = false
                        });
                });

            modelBuilder.Entity("_27_FrontToBackSqlConnection.Models.Slider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Subtitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Sliders");
                });
#pragma warning restore 612, 618
        }
    }
}
